spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:educertdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

server.port=8080
server.error.include-message=always

# Hedera API config (Replace with your actual keys from portal.hedera.com)
hedera.accountId=0.0.5615627
hedera.privateKey=302e020100300506032b657004220420c03951c5ef0237cf1ad492dbe90b8ecedd476fa7abf9f53dc9aa75abc1c8fb23
